steps:
  # Docker Build
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/test-project-randomtrees/test-project-docker:$SHORT_SHA', '.']
    
  # Docker push
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/test-project-randomtrees/test-project-docker:$SHORT_SHA']
    
  # Cloud run
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', 'test-project-docker', '--region=us-central1', '--platform=managed', '--image=gcr.io/test-project-randomtrees/test-project-docker:$SHORT_SHA']
    
    
  
  
