steps:
  # Docker Build
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/test-project-randomtrees/test-project-docker:$SHORT_SHA', '.']
    
  # Docker push
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/test-project-randomtrees/test-project-docker:$SHORT_SHA']
    
  # Cloud run
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', 'test-project-randomtrees', '--region=us-central1', '--platform=managed', '--image=gcr.io/test-project-randomtrees/test-project-docker:$SHORT_SHA']
    
options:
  logging: CLOUD_LOGGING_ONLY
#serviceAccount: 'projects/test-project-randomtrees/serviceAccounts/randomtrees-admin@test-project-randomtrees.iam.gserviceaccount.com'
  
